#!/usr/bin/env sh
#
# PHPStan / Analyze application and framework classes (Linux)
#
# @template-version 1.2
#
# @template-version 1.2
#

MemoryLimit=900M
AnalysisLevel=5
OutputFile=docs/phpstan/result.txt
ConfigFile=docs/phpstan/config.neon
BinFolder=vendor/bin

echo "-------------------------------------------------------"
echo "RUNNING PHPSTAN"
echo "-------------------------------------------------------"
echo ""

$BinFolder/phpstan analyse -l $AnalysisLevel -c $ConfigFile --memory-limit=$MemoryLimit src/classes > $OutputFile
