<?php

abstract class Application_Admin_Area_Mode_Submode_Action_RevisionableSettings extends Application_Admin_Area_Mode_Submode_Action_Revisionable
{
    use Application_Admin_RevisionableSettings;
}
