<?php

declare(strict_types=1);

namespace AppFrameworkTests\Composer\ModulesOverview;

use AppUtils\FileHelper\FileInfo;
use AppUtils\FileHelper\FolderInfo;
use Application\Composer\ModulesOverview\ModulesOverviewGenerator;
use AppFrameworkTestClasses\ApplicationTestCase;

/**
 * Integration tests for {@see ModulesOverviewGenerator}.
 * Runs the full generator against the framework's own module structure.
 */
final class ModulesOverviewGeneratorTest extends ApplicationTestCase
{
    /**
     * The generated output file path, relative to the framework root.
     */
    private const OUTPUT_RELATIVE_PATH = '/docs/agents/project-manifest/modules-overview.md';

    /**
     * Known Application Framework module IDs that must appear in the output.
     */
    private const FRAMEWORK_MODULE_IDS = array(
        'connectors',
        'db-helper',
        'event-handler',
        'application-sets',
    );

    private static FolderInfo $rootFolder;
    private static string $outputPath;
    private static string $outputContent = '';

    public static function setUpBeforeClass() : void
    {
        parent::setUpBeforeClass();

        $frameworkRoot = realpath(__DIR__ . '/../../../../') ?: __DIR__ . '/../../../../';

        self::$rootFolder  = FolderInfo::factory($frameworkRoot);
        self::$outputPath  = rtrim($frameworkRoot, '/') . self::OUTPUT_RELATIVE_PATH;

        (new ModulesOverviewGenerator(self::$rootFolder))->generate();
        self::$outputContent = FileInfo::factory(self::$outputPath)->getContents();
    }

    private function createGenerator() : ModulesOverviewGenerator
    {
        return new ModulesOverviewGenerator(self::$rootFolder);
    }

    private function stripTimestamp(string $content) : string
    {
        return (string)preg_replace('/^> Auto-generated on .+$/m', '> Auto-generated on [TIMESTAMP].', $content);
    }

    // -------------------------------------------------------------------------
    // Tests
    // -------------------------------------------------------------------------

    /**
     * Running generate() must produce a non-empty file at the expected path.
     */
    public function test_generate_createsFile() : void
    {
        $this->assertFileExists(self::$outputPath);
        $this->assertNotEmpty(self::$outputContent);
    }

    /**
     * The output file must contain the auto-generated header notice.
     */
    public function test_generate_containsAutoGeneratedNotice() : void
    {
        $this->assertStringContainsString('Auto-generated on', self::$outputContent);
        $this->assertStringContainsString('Do not edit manually.', self::$outputContent);
    }

    /**
     * All known Application Framework module IDs must appear in the output.
     */
    public function test_generate_allFrameworkModulesPresent() : void
    {
        foreach(self::FRAMEWORK_MODULE_IDS as $moduleId)
        {
            $this->assertStringContainsString(
                $moduleId,
                self::$outputContent,
                sprintf('Framework module "%s" must be listed in the output.', $moduleId)
            );
        }
    }

    /**
     * The framework Composer package name must appear as a section heading.
     */
    public function test_generate_packageGroupingPresent() : void
    {
        $this->assertStringContainsString(
            'mistralys/application_framework',
            self::$outputContent,
            'Application Framework Composer package heading must be present.'
        );
    }

    /**
     * Running the generator twice must produce identical content
     * (excluding the timestamp line).
     */
    public function test_generate_idempotent() : void
    {
        $generator = $this->createGenerator();

        $generator->generate();
        $firstRun = $this->stripTimestamp(FileInfo::factory(self::$outputPath)->getContents());

        $generator->generate();
        $secondRun = $this->stripTimestamp(FileInfo::factory(self::$outputPath)->getContents());

        $this->assertSame(
            $firstRun,
            $secondRun,
            'Two successive generator runs must produce the same output (excluding the timestamp).'
        );
    }
}
