<?php

declare(strict_types=1);

namespace AppFrameworkTests\Composer\ModulesOverview;

use Application\Composer\ModulesOverview\ModuleInfo;
use Application\Composer\ModulesOverview\ModulesOverviewRenderer;
use AppFrameworkTestClasses\ApplicationTestCase;

/**
 * Unit tests for {@see ModulesOverviewRenderer}.
 * Uses manually constructed ModuleInfo objects — no filesystem dependency.
 */
final class ModulesOverviewRendererTest extends ApplicationTestCase
{
    private function makeModule(
        string $id,
        string $label,
        string $description,
        array  $relatedModules,
        string $sourcePath,
        string $contextOutput,
        string $composerPackage
    ) : ModuleInfo
    {
        return new ModuleInfo(
            $id,
            $label,
            $description,
            $relatedModules,
            $sourcePath,
            $contextOutput,
            $composerPackage
        );
    }

    public function test_render_containsAutoGeneratedNotice() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule('mod-a', 'Module A', 'Desc A.', array(), 'src/A/', '.context/modules/a/', 'vendor/package-a'),
        ));

        $output = $renderer->render();

        $this->assertStringContainsString('Auto-generated on', $output);
        $this->assertStringContainsString('Do not edit manually.', $output);
    }

    public function test_render_groupsByPackageName() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule('mod-a', 'Module A', 'Desc A.', array(), 'src/A/', '.context/modules/a/', 'vendor/package-alpha'),
            $this->makeModule('mod-b', 'Module B', 'Desc B.', array(), 'src/B/', '.context/modules/b/', 'vendor/package-beta'),
        ));

        $output = $renderer->render();

        $this->assertStringContainsString('## vendor/package-alpha', $output);
        $this->assertStringContainsString('## vendor/package-beta', $output);
    }

    public function test_render_sortsPackagesAlphabetically() : void
    {
        // Supply packages in reverse order (zeta before alpha)
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule('mod-z', 'Module Z', 'Desc Z.', array(), 'src/Z/', '.context/modules/z/', 'vendor/package-zeta'),
            $this->makeModule('mod-a', 'Module A', 'Desc A.', array(), 'src/A/', '.context/modules/a/', 'vendor/package-alpha'),
        ));

        $output = $renderer->render();

        $posAlpha = strpos($output, '## vendor/package-alpha');
        $posZeta  = strpos($output, '## vendor/package-zeta');

        $this->assertNotFalse($posAlpha, 'alpha heading should be present');
        $this->assertNotFalse($posZeta, 'zeta heading should be present');
        $this->assertLessThan($posZeta, $posAlpha, 'alpha should appear before zeta');
    }

    public function test_render_sortsModulesByID() : void
    {
        // Supply modules in reverse ID order (zebra before apple)
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule('zebra', 'Zebra Module', 'Desc.', array(), 'src/Z/', '.context/modules/z/', 'vendor/package-a'),
            $this->makeModule('apple', 'Apple Module', 'Desc.', array(), 'src/A/', '.context/modules/a/', 'vendor/package-a'),
        ));

        $output = $renderer->render();

        $posApple = strpos($output, '`apple`');
        $posZebra = strpos($output, '`zebra`');

        $this->assertNotFalse($posApple, 'apple row should be present');
        $this->assertNotFalse($posZebra, 'zebra row should be present');
        $this->assertLessThan($posZebra, $posApple, 'apple should appear before zebra');
    }

    public function test_render_includesAllTableColumns() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule('mod-a', 'Module A', 'Desc A.', array(), 'src/A/', '.context/modules/a/', 'vendor/package-a'),
        ));

        $output = $renderer->render();

        $this->assertStringContainsString('| ID |', $output);
        $this->assertStringContainsString('| Label |', $output);
        $this->assertStringContainsString('| Description |', $output);
        $this->assertStringContainsString('| Source Path |', $output);
        $this->assertStringContainsString('| Context Docs |', $output);
        $this->assertStringContainsString('| Related Modules |', $output);
    }

    public function test_render_relatedModulesShownAsList() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule(
                'comtypes',
                'Communication Types',
                'Manages comtypes.',
                array('tenants', 'variables'),
                'assets/classes/Maileditor/Comtypes/',
                '.context/modules/comtypes/',
                'vendor/maileditor'
            ),
        ));

        $output = $renderer->render();

        $this->assertStringContainsString('tenants, variables', $output);
    }

    public function test_render_emptyRelatedModulesShowsDash() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule('mod-a', 'Module A', 'Desc A.', array(), 'src/A/', '.context/modules/a/', 'vendor/package-a'),
        ));

        $output = $renderer->render();

        // The em-dash should appear in the related modules column
        $this->assertStringContainsString('| — |', $output);
    }

    public function test_render_relationshipsSectionListed() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule(
                'comtypes',
                'Communication Types',
                'Manages comtypes.',
                array('tenants', 'variables'),
                'assets/classes/Maileditor/Comtypes/',
                '.context/modules/comtypes/',
                'vendor/maileditor'
            ),
            $this->makeModule(
                'tenants',
                'Tenants',
                'Manages tenants.',
                array(),
                'assets/classes/Maileditor/Tenants/',
                '.context/modules/tenants/',
                'vendor/maileditor'
            ),
        ));

        $output = $renderer->render();

        $this->assertStringContainsString('**comtypes** → tenants', $output);
    }

    public function test_render_modulesWithoutRelationshipsOmittedFromRelationshipsSection() : void
    {
        $renderer = new ModulesOverviewRenderer(array(
            $this->makeModule(
                'comtypes',
                'Communication Types',
                'Manages comtypes.',
                array('tenants'),
                'assets/classes/Maileditor/Comtypes/',
                '.context/modules/comtypes/',
                'vendor/maileditor'
            ),
            $this->makeModule(
                'tenants',
                'Tenants',
                'Manages tenants.',
                array(),
                'assets/classes/Maileditor/Tenants/',
                '.context/modules/tenants/',
                'vendor/maileditor'
            ),
        ));

        $output = $renderer->render();

        // comtypes has relationships and should appear in the section
        $this->assertStringContainsString('**comtypes**', $output);

        // tenants has no outgoing relationships and must not have its own bullet entry
        $this->assertStringNotContainsString('**tenants** →', $output);
    }
}
