#!/usr/bin/env sh
#
# PHPStan / Analyze application and framework classes (Linux)
#

MemoryLimit=900M
AnalysisLevel=5
OutputFile=./result.txt
ConfigFile=./config.neon
BinFolder=./../../vendor/bin

echo "-------------------------------------------------------"
echo "RUNNING PHPSTAN @ LEVEL $AnalysisLevel"
echo "-------------------------------------------------------"
echo ""

$BinFolder/phpstan analyse -l $AnalysisLevel -c $ConfigFile --memory-limit=$MemoryLimit > $OutputFile

echo ""
echo "Saved to $OutputFile."
echo ""
