<?php
/**
 * @package Application
 * @subpackage Composer
 */

declare(strict_types=1);

namespace Application\Composer\KeywordGlossary;

/**
 * Renders a Markdown keyword-glossary document from pre-sorted
 * {@see KeywordEntry} and {@see GlossarySection} collections.
 *
 * The caller is responsible for sorting both collections before construction.
 * Uses LF-only ("\n") line endings for OS-independent output.
 *
 * @package Application
 * @subpackage Composer
 */
final class KeywordGlossaryRenderer
{
    /**
     * @var KeywordEntry[]
     */
    private array $keywords;

    /**
     * @var GlossarySection[]
     */
    private array $sections;

    /**
     * @param KeywordEntry[]    $keywords Pre-sorted keyword entries.
     * @param GlossarySection[] $sections Custom sections contributed via the
     *                                    {@see \Application\Composer\KeywordGlossary\Events\DecorateGlossaryEvent}.
     */
    public function __construct(array $keywords, array $sections)
    {
        $this->keywords = $keywords;
        $this->sections = $sections;
    }

    /**
     * Returns the keyword entries.
     *
     * @return KeywordEntry[]
     */
    public function getKeywords() : array
    {
        return $this->keywords;
    }

    /**
     * Returns the custom glossary sections.
     *
     * @return GlossarySection[]
     */
    public function getSections() : array
    {
        return $this->sections;
    }

    /**
     * Builds and returns the complete Markdown document string.
     *
     * @return string
     */
    public function render() : string
    {
        // NOTE: "\n" is used intentionally throughout — PHP_EOL must NOT be used here
        // because the generated file must have OS-independent (LF) line endings.
        $now = gmdate('Y-m-d\TH:i:s\Z');

        $lines = array();
        $lines[] = '> **Auto-generated** — do not edit. Regenerated by `composer build-dev`.';
        $lines[] = '> Generated: ' . $now;
        $lines[] = '';
        $lines[] = '# Keyword Glossary';
        $lines[] = '';
        $lines[] = '| Keyword | Context | Module(s) |';
        $lines[] = '|---------|---------|-----------|';

        foreach($this->keywords as $entry)
        {
            $keyword = str_replace('|', '&#124;', $entry->getKeyword());
            $context = $entry->getContext() !== '' ? str_replace('|', '&#124;', $entry->getContext()) : '—';
            $modules = str_replace('|', '&#124;', implode(', ', $entry->getModuleIds()));
            $lines[] = '| ' . $keyword . ' | ' . $context . ' | ' . $modules . ' |';
        }

        foreach($this->sections as $section)
        {
            $lines[] = '';
            foreach($this->renderSection($section) as $line)
            {
                $lines[] = $line;
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Renders a single glossary section as an array of Markdown lines.
     *
     * Produces the section heading (`## {heading}`), a Markdown table
     * header with the section's column headers, and one table row per
     * {@see GlossarySectionEntry}.
     *
     * @param GlossarySection $section
     * @return string[]
     */
    public function renderSection(GlossarySection $section) : array
    {
        $lines = array();
        $lines[] = '## ' . $section->getHeading();
        $lines[] = '';

        $headers = $section->getColumnHeaders();

        if(empty($headers))
        {
            return $lines;
        }

        $escapedHeaders = array_map(
            static function(string $h) : string { return str_replace('|', '&#124;', $h); },
            $headers
        );

        $lines[] = '| ' . implode(' | ', $escapedHeaders) . ' |';
        $lines[] = '|' . implode('|', array_fill(0, count($headers), '------')) . '|';

        foreach($section->getEntries() as $entry)
        {
            $values = array_map(
                static function(string $v) : string { return str_replace('|', '&#124;', $v); },
                $entry->getValues()
            );
            $lines[] = '| ' . implode(' | ', $values) . ' |';
        }

        return $lines;
    }
}
