<?php

declare(strict_types=1);

namespace AppFrameworkTests\API\OpenAPI;

use Application\API\OpenAPI\HtaccessGenerator;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for {@see HtaccessGenerator}.
 *
 * Verifies that the generated `.htaccess` content is correct for both the
 * default and custom `RewriteBase` configurations, and that `generate()`
 * writes the file to disk and returns the correct path.
 */
final class HtaccessGeneratorTest extends TestCase
{
    private string $tempDir = '';

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir().'/htaccess_generator_test_'.uniqid('', true);
        mkdir($this->tempDir, 0777, true);
    }

    protected function tearDown(): void
    {
        $htaccess = $this->tempDir.'/'.HtaccessGenerator::HTACCESS_FILENAME;
        if(file_exists($htaccess)) {
            unlink($htaccess);
        }
        if(is_dir($this->tempDir)) {
            rmdir($this->tempDir);
        }
    }

    // -------------------------------------------------------------------------
    // Content generation — default RewriteBase
    // -------------------------------------------------------------------------

    public function test_getContent_returnsNonEmptyString() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);

        $this->assertNotEmpty($generator->getContent());
        $this->assertGreaterThan(0, strlen($generator->getContent()));
    }

    public function test_getContent_containsIfModuleBlock() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        $this->assertStringContainsString('<IfModule mod_rewrite.c>', $content);
        $this->assertStringContainsString('</IfModule>', $content);
    }

    public function test_getContent_containsRewriteEngineOn() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        $this->assertStringContainsString('RewriteEngine On', $content);
    }

    public function test_getContent_defaultRewriteBase() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        // When DEFAULT_REWRITE_BASE is empty the RewriteBase directive is omitted entirely.
        $this->assertStringNotContainsString('RewriteBase', $content);
    }

    public function test_getContent_containsRequestFilenameCondition() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        $this->assertStringContainsString('RewriteCond %{REQUEST_FILENAME} -f', $content);
    }

    public function test_getContent_containsGenericRewriteRule() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        // Rule must match PascalCase method names and rewrite to index.php?method=$1
        $this->assertStringContainsString('RewriteRule ^([A-Za-z][A-Za-z0-9]*)$ index.php?method=$1', $content);
    }

    public function test_getContent_containsQsaFlag() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        $this->assertStringContainsString('[QSA,L]', $content);
    }

    public function test_getContent_containsAutoGeneratedComment() : void
    {
        $content = (new HtaccessGenerator($this->tempDir))->getContent();

        $this->assertStringContainsString('Auto-generated by OpenAPIGenerator', $content);
    }

    // -------------------------------------------------------------------------
    // Custom RewriteBase
    // -------------------------------------------------------------------------

    public function test_setRewriteBase_affectsContent() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $generator->setRewriteBase('/myapp/api/');

        $content = $generator->getContent();

        $this->assertStringContainsString('RewriteBase /myapp/api/', $content);
        $this->assertStringNotContainsString('RewriteBase /api/', $content);
    }

    public function test_setRewriteBase_returnsSelf() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $result = $generator->setRewriteBase('/custom/api/');

        $this->assertSame($generator, $result);
    }

    public function test_getRewriteBase_returnsDefault() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);

        $this->assertSame(HtaccessGenerator::DEFAULT_REWRITE_BASE, $generator->getRewriteBase());
    }

    public function test_getRewriteBase_returnsConfiguredValue() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $generator->setRewriteBase('/subdirectory/api/');

        $this->assertSame('/subdirectory/api/', $generator->getRewriteBase());
    }

    // -------------------------------------------------------------------------
    // File generation
    // -------------------------------------------------------------------------

    public function test_generate_writesFile() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $generator->generate();

        $this->assertFileExists($this->tempDir.'/'.HtaccessGenerator::HTACCESS_FILENAME);
    }

    public function test_generate_returnsFilePath() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $returnedPath = $generator->generate();

        $this->assertSame($this->tempDir.'/'.HtaccessGenerator::HTACCESS_FILENAME, $returnedPath);
    }

    public function test_generate_fileContentMatchesGetContent() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $expectedContent = $generator->getContent();
        $filePath = $generator->generate();

        $this->assertSame($expectedContent, file_get_contents($filePath));
    }

    public function test_generate_withCustomRewriteBase() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);
        $generator->setRewriteBase('/app/api/');
        $filePath = $generator->generate();

        $fileContent = file_get_contents($filePath);
        $this->assertIsString($fileContent);
        $this->assertStringContainsString('RewriteBase /app/api/', $fileContent);
    }

    // -------------------------------------------------------------------------
    // getFilePath
    // -------------------------------------------------------------------------

    public function test_getFilePath_includesHtaccessFilename() : void
    {
        $generator = new HtaccessGenerator($this->tempDir);

        $this->assertSame(
            $this->tempDir.'/'.HtaccessGenerator::HTACCESS_FILENAME,
            $generator->getFilePath()
        );
    }

    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------

    public function test_defaultRewriteBaseConstant() : void
    {
        $this->assertSame('', HtaccessGenerator::DEFAULT_REWRITE_BASE);
    }

    public function test_htaccessFilenameConstant() : void
    {
        $this->assertSame('.htaccess', HtaccessGenerator::HTACCESS_FILENAME);
    }
}
