<?php

declare(strict_types=1);

namespace AppFrameworkTests\Composer\KeywordGlossary;

use Application\Composer\KeywordGlossary\GlossarySection;
use Application\Composer\KeywordGlossary\GlossarySectionEntry;
use Application\Composer\KeywordGlossary\KeywordEntry;
use Application\Composer\KeywordGlossary\KeywordGlossaryRenderer;
use AppFrameworkTestClasses\ApplicationTestCase;

/**
 * Unit tests for {@see KeywordGlossaryRenderer}.
 * Uses manually constructed fixtures — no DB, no filesystem dependency.
 */
final class KeywordGlossaryRendererTest extends ApplicationTestCase
{
    // -------------------------------------------------------------------------
    // Fixtures
    // -------------------------------------------------------------------------

    private function makeKeyword(string $keyword, string $context, array $moduleIds) : KeywordEntry
    {
        return new KeywordEntry($keyword, $context, $moduleIds);
    }

    private function makeSection(string $heading, array $columnHeaders, array $rows) : GlossarySection
    {
        $entries = array();
        foreach($rows as $values)
        {
            $entries[] = new GlossarySectionEntry($values);
        }

        return new GlossarySection($heading, $columnHeaders, $entries);
    }

    // -------------------------------------------------------------------------
    // Tests
    // -------------------------------------------------------------------------

    /**
     * The auto-generated warning notice must appear at the top of every output.
     */
    public function test_render_containsAutoGeneratedHeader() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array($this->makeKeyword('ALPHA', 'some context', array('mod-a'))),
            array()
        );

        $output = $renderer->render();

        $this->assertStringContainsString('**Auto-generated**', $output);
        $this->assertStringContainsString('do not edit', $output);
    }

    /**
     * The keyword table must include the expected column headers.
     */
    public function test_render_containsKeywordTableHeader() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array($this->makeKeyword('BETA', '', array('mod-a'))),
            array()
        );

        $output = $renderer->render();

        $this->assertStringContainsString('| Keyword | Context | Module(s) |', $output);
    }

    /**
     * Keywords supplied in order must appear in the output in the same order.
     * The renderer preserves the order of the supplied array.
     */
    public function test_render_keywordsAppearsInSuppliedOrder() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array(
                $this->makeKeyword('Apple', 'first fruit', array('mod-a')),
                $this->makeKeyword('Zebra', 'last animal', array('mod-b')),
            ),
            array()
        );

        $output = $renderer->render();

        $posApple = strpos($output, 'Apple');
        $posZebra = strpos($output, 'Zebra');

        $this->assertNotFalse($posApple, 'Apple must appear in the output.');
        $this->assertNotFalse($posZebra, 'Zebra must appear in the output.');
        $this->assertLessThan($posZebra, $posApple, 'Apple must appear before Zebra.');
    }

    /**
     * When a keyword is shared by multiple modules, the Module(s) column must
     * show all module IDs as a comma-separated string.
     */
    public function test_render_multipleModulesShownAsCommaSeparated() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array($this->makeKeyword('SHARED', 'shared keyword', array('mod-alpha', 'mod-beta'))),
            array()
        );

        $output = $renderer->render();

        $this->assertStringContainsString('mod-alpha, mod-beta', $output);
    }

    /**
     * When a keyword has no context (empty string), the Context column must
     * display an em-dash ('—') instead of an empty cell.
     */
    public function test_render_emptyContextShowsEmDash() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array($this->makeKeyword('NOCONTEXT', '', array('mod-a'))),
            array()
        );

        $output = $renderer->render();

        $this->assertStringContainsString('| — |', $output);
    }

    /**
     * The section heading must appear as a Markdown H2 in the output.
     */
    public function test_render_containsSectionHeading() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array(),
            array($this->makeSection('Custom Section', array('Name', 'Value'), array()))
        );

        $output = $renderer->render();

        $this->assertStringContainsString('## Custom Section', $output);
    }

    /**
     * Section entries must appear as table rows in the output.
     */
    public function test_render_sectionEntriesAppearInOutput() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array(),
            array(
                $this->makeSection(
                    'Tenants',
                    array('Tenant', 'Country / Region'),
                    array(
                        array('IONOS', 'DE, ES, FR'),
                        array('STRATO', 'DE'),
                    )
                )
            )
        );

        $output = $renderer->render();

        $this->assertStringContainsString('IONOS', $output);
        $this->assertStringContainsString('DE, ES, FR', $output);
        $this->assertStringContainsString('STRATO', $output);
    }

    /**
     * With no keywords, the keyword table header and separator must be immediately
     * followed by the first section heading.
     */
    public function test_render_emptyKeywordListImmediatelyFollowedBySection() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array(),
            array($this->makeSection('My Section', array('Col A'), array()))
        );

        $output = $renderer->render();

        $this->assertStringContainsString('| Keyword | Context | Module(s) |', $output);
        $this->assertStringContainsString(
            '|---------|---------|-----------|\n\n## My Section',
            str_replace(array("\r\n", "\n"), '\n', $output)
        );
    }

    /**
     * With no sections, the document must end after the last keyword row.
     */
    public function test_render_noSectionsDocumentEndsAfterKeywords() : void
    {
        $renderer = new KeywordGlossaryRenderer(
            array($this->makeKeyword('ONLY', 'one keyword', array('mod-a'))),
            array()
        );

        $output = $renderer->render();

        // No section headings should appear
        $this->assertStringNotContainsString('## ', $output);
    }

    /**
     * renderSection() must render the section's column headers as a Markdown table header row.
     */
    public function test_renderSection_rendersColumnHeaders() : void
    {
        $renderer = new KeywordGlossaryRenderer(array(), array());
        $section  = $this->makeSection('Test Heading', array('Col A', 'Col B', 'Col C'), array());

        $lines = $renderer->renderSection($section);
        $joined = implode("\n", $lines);

        $this->assertStringContainsString('| Col A | Col B | Col C |', $joined);
    }

    /**
     * renderSection() must render one row per GlossarySectionEntry.
     */
    public function test_renderSection_rendersRows() : void
    {
        $renderer = new KeywordGlossaryRenderer(array(), array());
        $section  = $this->makeSection(
            'Section',
            array('Name', 'Region'),
            array(
                array('Alpha', 'DE'),
                array('Beta',  'AT'),
            )
        );

        $lines  = $renderer->renderSection($section);
        $joined = implode("\n", $lines);

        $this->assertStringContainsString('| Alpha | DE |', $joined);
        $this->assertStringContainsString('| Beta | AT |', $joined);
    }

    /**
     * renderSection() with no column headers must return only the heading lines.
     */
    public function test_renderSection_emptyColumnsReturnsHeadingOnly() : void
    {
        $renderer = new KeywordGlossaryRenderer(array(), array());
        $section  = $this->makeSection('Headless', array(), array());

        $lines = $renderer->renderSection($section);

        $this->assertCount(2, $lines, 'Only the heading line and blank line should be returned when no column headers are present.');
        $this->assertSame('## Headless', $lines[0]);
    }
}
