<?php

declare(strict_types=1);

namespace AppFrameworkTests\Composer\KeywordGlossary;

use AppUtils\FileHelper\FileInfo;
use AppUtils\FileHelper\FolderInfo;
use Application\Composer\KeywordGlossary\KeywordGlossaryGenerator;
use AppFrameworkTestClasses\ApplicationTestCase;

/**
 * Integration tests for {@see KeywordGlossaryGenerator}.
 * Uses temporary fixture directories and YAML files since the framework's own
 * module-context.yaml files do not define any keywords.
 */
final class KeywordGlossaryGeneratorTest extends ApplicationTestCase
{
    /**
     * Unique sentinel tokens used in fixtures.
     * These must NOT match any keyword in real project YAML files.
     */
    private const FIXTURE_KEYWORD_A = 'TESTKEYWORD_ALPHA_FW_UNIQUE';
    private const FIXTURE_KEYWORD_B = 'TESTKEYWORD_BETA_FW_UNIQUE';

    private string $tempRoot   = '';
    private string $tempOutput = '';

    protected function setUp() : void
    {
        parent::setUp();

        $this->tempRoot   = sys_get_temp_dir() . '/kgg-fw-test-' . getmypid() . '-' . mt_rand(0, 9999);
        $this->tempOutput = $this->tempRoot . '/output.md';

        $this->buildFixtureRoot();
    }

    protected function tearDown() : void
    {
        $this->removeFixtureRoot();
        parent::tearDown();
    }

    // -------------------------------------------------------------------------
    // Fixture helpers
    // -------------------------------------------------------------------------

    /**
     * Builds a fixture root with two modules bearing the sentinel keywords.
     */
    private function buildFixtureRoot() : void
    {
        $this->writeRootContextYaml($this->tempRoot);

        $this->writeModuleContextYaml(
            $this->tempRoot . '/fixture-module-alpha',
            'fixture-mod-alpha',
            array(self::FIXTURE_KEYWORD_A . ' (sentinel for module alpha)')
        );

        $this->writeModuleContextYaml(
            $this->tempRoot . '/fixture-module-beta',
            'fixture-mod-beta',
            array(self::FIXTURE_KEYWORD_B . ' (sentinel for module beta)')
        );
    }

    private function writeRootContextYaml(string $rootDir) : void
    {
        if(!is_dir($rootDir))
        {
            mkdir($rootDir, 0777, true);
        }

        $yaml = "import:\n  - path: \"**/module-context.yaml\"\n";
        file_put_contents($rootDir . '/context.yaml', $yaml);
    }

    private function writeModuleContextYaml(string $dirPath, string $moduleId, array $keywords) : void
    {
        if(!is_dir($dirPath))
        {
            mkdir($dirPath, 0777, true);
        }

        $keywordLines = '';
        foreach($keywords as $kw)
        {
            $keywordLines .= '    - ' . $kw . "\n";
        }

        $yaml = "moduleMetaData:\n" .
                '  id: "' . $moduleId . '"' . "\n" .
                "  keywords:\n" .
                $keywordLines;

        file_put_contents($dirPath . '/module-context.yaml', $yaml);
    }

    private function removeFixtureRoot() : void
    {
        $paths = array(
            $this->tempRoot . '/fixture-module-alpha/module-context.yaml',
            $this->tempRoot . '/fixture-module-beta/module-context.yaml',
            $this->tempRoot . '/context.yaml',
            $this->tempOutput,
        );

        foreach($paths as $path)
        {
            if(file_exists($path)) { unlink($path); }
        }

        $dirs = array(
            $this->tempRoot . '/fixture-module-alpha',
            $this->tempRoot . '/fixture-module-beta',
            $this->tempRoot,
        );

        foreach($dirs as $dir)
        {
            if(is_dir($dir)) { rmdir($dir); }
        }
    }

    private function runGenerator() : string
    {
        (new KeywordGlossaryGenerator(FolderInfo::factory($this->tempRoot)))->generate($this->tempOutput);
        return FileInfo::factory($this->tempOutput)->getContents();
    }

    private function stripTimestamp(string $content) : string
    {
        return (string)preg_replace('/^> Generated: .+$/m', '> Generated: [TIMESTAMP]', $content);
    }

    // -------------------------------------------------------------------------
    // Tests
    // -------------------------------------------------------------------------

    /**
     * Running generate() must create a non-empty output file.
     */
    public function test_generate_createsOutputFile() : void
    {
        $content = $this->runGenerator();

        $this->assertFileExists($this->tempOutput);
        $this->assertNotEmpty($content);
    }

    /**
     * The output must contain the auto-generated header notice.
     */
    public function test_generate_outputContainsAutoGeneratedHeader() : void
    {
        $content = $this->runGenerator();

        $this->assertStringContainsString('**Auto-generated**', $content);
        $this->assertStringContainsString('do not edit', $content);
    }

    /**
     * Both sentinel keywords from the fixture modules must appear in the output.
     */
    public function test_generate_keywordsFromFixtureModulesPresent() : void
    {
        $content = $this->runGenerator();

        $this->assertStringContainsString(
            self::FIXTURE_KEYWORD_A,
            $content,
            'Sentinel keyword A must appear in the fixture-based output.'
        );

        $this->assertStringContainsString(
            self::FIXTURE_KEYWORD_B,
            $content,
            'Sentinel keyword B must appear in the fixture-based output.'
        );
    }

    /**
     * Both fixture module IDs must appear in the Module(s) column.
     */
    public function test_generate_moduleIDsAppearInOutput() : void
    {
        $content = $this->runGenerator();

        $this->assertStringContainsString('fixture-mod-alpha', $content);
        $this->assertStringContainsString('fixture-mod-beta', $content);
    }

    /**
     * Running the generator twice must produce identical content
     * (excluding the timestamp line).
     */
    public function test_generate_idempotent() : void
    {
        $firstRun  = $this->stripTimestamp($this->runGenerator());
        $secondRun = $this->stripTimestamp($this->runGenerator());

        $this->assertSame(
            $firstRun,
            $secondRun,
            'Two successive generator runs must produce the same output (excluding the timestamp).'
        );
    }

    /**
     * The keyword table header must be present in the output.
     */
    public function test_generate_keywordTableHeaderPresent() : void
    {
        $content = $this->runGenerator();

        $this->assertStringContainsString('| Keyword | Context | Module(s) |', $content);
    }
}
