<?php
/**
 * @package API
 * @subpackage OpenAPI
 */

declare(strict_types=1);

namespace Application\API\OpenAPI;

use Application\API\APIManager;
use Application\API\BaseMethods\BaseAPIMethod;
use Application\API\ErrorResponse;
use Application\API\Groups\APIGroupInterface;
use Application\API\Groups\FrameworkAPIGroup;
use Application\API\Parameters\Validation\ParamValidationResults;
use Application\API\Traits\JSONResponseInterface;
use Application\API\Traits\JSONResponseTrait;
use Application\API\Traits\RequestRequestInterface;
use Application\API\Traits\RequestRequestTrait;
use Application\API\Utilities\KeyDescription;
use AppUtils\ArrayDataCollection;

/**
 * Framework-built-in API method that returns the pre-generated OpenAPI 3.1 specification
 * ({@see OpenAPIGenerator::DEFAULT_OUTPUT_RELATIVE}) as raw JSON.
 *
 * ## Response
 *
 * Unlike most framework API methods this method bypasses the standard JSON envelope and
 * returns the raw OpenAPI specification document.  The `Content-Type` header is set to
 * `application/json` so the response can be consumed directly by Swagger UI and similar
 * tools.
 *
 * ## Error handling
 *
 * If the spec file has not been generated yet (e.g. `composer build` has not been run),
 * the method returns a `500 Internal Server Error` with a standard JSON error envelope
 * pointing to the missing file path.
 *
 * ## Accessing the spec
 *
 * The method is reachable at `/api/GetOpenAPISpec` when the `.htaccess` generated by
 * {@see HtaccessGenerator} is in place, or at `/api/index.php?method=GetOpenAPISpec`
 * without the rewrite rules.
 *
 * @package API
 * @subpackage OpenAPI
 */
class GetOpenAPISpec extends BaseAPIMethod implements RequestRequestInterface, JSONResponseInterface
{
    use RequestRequestTrait;
    use JSONResponseTrait;

    public const string METHOD_NAME = 'GetOpenAPISpec';

    public const int ERROR_SPEC_NOT_GENERATED = 1;

    public const string VERSION_1_0 = '1.0';
    public const string CURRENT_VERSION = self::VERSION_1_0;

    private string $specJSON = '';

    // -------------------------------------------------------------------------
    // APIMethodInterface — identity
    // -------------------------------------------------------------------------

    public function getMethodName(): string
    {
        return self::METHOD_NAME;
    }

    public function getDescription(): string
    {
        return 'Returns the pre-generated OpenAPI 3.1 specification for all API methods as raw JSON.';
    }

    public function getGroup(): APIGroupInterface
    {
        return FrameworkAPIGroup::create();
    }

    // -------------------------------------------------------------------------
    // APIMethodInterface — versioning
    // -------------------------------------------------------------------------

    public function getVersions(): array
    {
        return array(self::VERSION_1_0);
    }

    public function getCurrentVersion(): string
    {
        return self::CURRENT_VERSION;
    }

    public function getChangelog(): array
    {
        return array();
    }

    public function getRelatedMethodNames(): array
    {
        return array();
    }

    // -------------------------------------------------------------------------
    // JSONResponseInterface — documentation helpers
    // -------------------------------------------------------------------------

    /**
     * Returns an empty example because the response body is the raw OpenAPI spec,
     * not a standard JSON envelope.
     *
     * @return array<string, mixed>
     */
    public function getExampleJSONResponse(): array
    {
        return array();
    }

    /**
     * No standard response keys — the response is raw OpenAPI spec JSON.
     *
     * @return KeyDescription[]
     */
    public function getReponseKeyDescriptions(): array
    {
        return array();
    }

    // -------------------------------------------------------------------------
    // BaseAPIMethod — lifecycle hooks
    // -------------------------------------------------------------------------

    protected function init(): void
    {
        // No parameters required.
    }

    protected function collectRequestData(string $version): void
    {
        // No request data to collect.
    }

    protected function collectResponseData(ArrayDataCollection $response, string $version): void
    {
        $path = $this->resolveSpecPath();

        if(!is_file($path)) {
            $this->errorResponse(self::ERROR_SPEC_NOT_GENERATED)
                ->makeInternalServerError()
                ->setErrorMessage(
                    'The OpenAPI specification has not been generated yet. ' .
                    'Expected file: [%s]. Run [composer build] or [composer generate-openapi-spec] to generate it.',
                    $path
                )
                ->send();
        }

        $this->specJSON = (string)file_get_contents($path);
    }

    protected function configureValidationErrorResponse(ErrorResponse $response, ParamValidationResults $results): void
    {
        // No params to validate; provided for completeness.
    }

    // -------------------------------------------------------------------------
    // JSONResponseTrait override — raw JSON output (no envelope)
    // -------------------------------------------------------------------------

    /**
     * Overrides the trait's envelope-wrapping behaviour to output the specification
     * directly as the response body.
     *
     * The `HTTP/1.1 200 OK` header and CORS headers are already applied by the parent
     * `BaseAPIMethod::sendSuccessResponse()` before this method is invoked.
     *
     * @param ArrayDataCollection $data Ignored — raw JSON is stored on `$this->specJSON`.
     * @return void
     */
    protected function _sendSuccessResponse(ArrayDataCollection $data): void
    {
        header('Content-Type: application/json');
        echo $this->specJSON;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Returns the absolute path to the pre-generated OpenAPI spec file.
     *
     * Uses the `APP_INSTALL_FOLDER` constant when available, falling back to an
     * empty string (which will cause a "not generated" error at runtime).
     *
     * @return string
     */
    private function resolveSpecPath(): string
    {
        if(defined('APP_INSTALL_FOLDER')) {
            return APP_INSTALL_FOLDER.'/'.OpenAPIGenerator::DEFAULT_OUTPUT_RELATIVE;
        }

        return '';
    }

    // -------------------------------------------------------------------------
    // Static URL helper
    // -------------------------------------------------------------------------

    /**
     * Returns the absolute URL at which this method can be accessed.
     *
     * Appends `APP_URL` (when defined) to `/api/{METHOD_NAME}`, producing a
     * URL compatible with the `.htaccess` rewrite rules generated by
     * {@see HtaccessGenerator}.
     *
     * Example: `https://example.com/api/GetOpenAPISpec`
     *
     * @return string Empty string when `APP_URL` is not defined.
     */
    public static function getSpecURL(): string
    {
        if(defined('APP_URL')) {
            return APP_URL.'/api/'.self::METHOD_NAME;
        }

        return '';
    }
}
