<?php
/**
 * @package API
 * @subpackage OpenAPI
 */

declare(strict_types=1);

namespace Application\API\OpenAPI;

use AppUtils\FileHelper\FileInfo;
use AppUtils\FileHelper\FolderInfo;

/**
 * Generates an Apache `.htaccess` file in the application's `/api/` directory
 * that enables RESTful URL rewriting.
 *
 * ## Purpose
 *
 * The API currently dispatches all requests through `/api/index.php` using a
 * `method` query parameter. This generator produces a `.htaccess` file that
 * rewrites clean RESTful paths (`/api/GetComtypes`) to the existing dispatcher
 * (`/api/index.php?method=GetComtypes`), making the OpenAPI spec paths real,
 * callable URLs.
 *
 * ## Backward compatibility
 *
 * The old `?method=` query parameter dispatch is unaffected — `index.php` is
 * still served directly for those requests.
 *
 * ## Usage
 *
 * ```php
 * $generator = new HtaccessGenerator('/path/to/application/api');
 * $generator->setRewriteBase('/myapp/api/');
 * $filePath = $generator->generate(); // returns path to generated .htaccess
 * ```
 *
 * @package API
 * @subpackage OpenAPI
 */
class HtaccessGenerator
{
    public const string DEFAULT_REWRITE_BASE = '/api/';
    public const string HTACCESS_FILENAME = '.htaccess';

    private string $outputDirectory;
    private string $rewriteBase;

    /**
     * @param string $outputDirectory Absolute path to the directory where the `.htaccess` file will be written.
     *                                Typically the application's `api/` folder.
     */
    public function __construct(string $outputDirectory)
    {
        $this->outputDirectory = rtrim($outputDirectory, '/\\');
        $this->rewriteBase = self::DEFAULT_REWRITE_BASE;
    }

    /**
     * Sets the `RewriteBase` directive used in the generated `.htaccess`.
     *
     * The value should include the full path from the server root to the api
     * directory, e.g. `/myapp/api/` if the application is installed at `/myapp/`.
     * Defaults to `/api/`.
     *
     * @param string $rewriteBase The RewriteBase path, e.g. `/api/` or `/myapp/api/`.
     * @return $this
     */
    public function setRewriteBase(string $rewriteBase) : self
    {
        $this->rewriteBase = $rewriteBase;
        return $this;
    }

    /**
     * Returns the configured `RewriteBase` value.
     *
     * @return string
     */
    public function getRewriteBase() : string
    {
        return $this->rewriteBase;
    }

    /**
     * Returns the absolute path to the `.htaccess` file that would be generated.
     *
     * @return string
     */
    public function getFilePath() : string
    {
        return $this->outputDirectory.'/'.self::HTACCESS_FILENAME;
    }

    /**
     * Returns the full `.htaccess` content as a string without writing to disk.
     *
     * Useful for testing and previewing the generated output.
     *
     * @return string
     */
    public function getContent() : string
    {
        $lines = array(
            '# Auto-generated by OpenAPIGenerator — do not edit manually.',
            '# Rewrites RESTful API paths to the query-based dispatcher.',
            '# The old ?method= query parameter dispatch remains functional.',
            '',
            '<IfModule mod_rewrite.c>',
            '    RewriteEngine On',
            '    RewriteBase '.$this->rewriteBase,
            '',
            '    # Skip existing files (index.php, documentation.php, openapi.json)',
            '    RewriteCond %{REQUEST_FILENAME} -f',
            '    RewriteRule ^ - [L]',
            '',
            '    # Rewrite /api/{MethodName} → /api/index.php?method={MethodName}',
            '    RewriteRule ^([A-Za-z][A-Za-z0-9]*)$ index.php?method=$1 [QSA,L]',
            '</IfModule>',
        );

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /**
     * Generates the `.htaccess` file in the configured output directory.
     *
     * Creates the output directory if it does not exist, writes the file, and
     * returns the absolute path to the generated file.
     *
     * @return string The absolute path to the generated `.htaccess` file.
     */
    public function generate() : string
    {
        $filePath = $this->getFilePath();

        FileInfo::factory($filePath)->putContents($this->getContent());

        return $filePath;
    }
}
