<?php
/**
 * @package API
 * @subpackage OpenAPI
 */

declare(strict_types=1);

namespace Application\API\OpenAPI;

use Application\API\APIMethodInterface;
use Application\API\Clients\API\APIKeyMethodInterface;
use Application\API\Groups\APIGroupInterface;
use Application\API\Parameters\Rules\RuleInterface;
use Application\API\Parameters\Rules\Type\OrRule;
use Application\API\Parameters\Rules\Type\RequiredIfOtherIsSetRule;
use Application\API\Traits\JSONRequestInterface;

/**
 * Converts a single `APIMethodInterface` instance into a complete OpenAPI 3.1 path item object.
 *
 * This is the central composition layer that combines parameter conversion, response conversion,
 * and method-level metadata (tags, extensions, descriptions) into a single path entry.
 *
 * ## Path format
 *
 * All paths follow the pattern `/api/{MethodName}`, matching the `.htaccess` rewrite rules
 * generated by {@see HtaccessGenerator}.
 *
 * ## HTTP method
 *
 * All framework API endpoints use `POST`. Each path item contains only a `post` operation.
 *
 * ## Composition
 *
 * - Parameter conversion is delegated to {@see ParameterConverter}.
 * - Response conversion is delegated to {@see ResponseConverter}.
 * - The global `apiVersion` query parameter is added manually (since {@see ParameterConverter}
 *   intentionally skips reserved parameters).
 *
 * @package API
 * @subpackage OpenAPI
 */
class MethodConverter
{
    private ResponseConverter $responseConverter;

    public function __construct()
    {
        $this->responseConverter = new ResponseConverter();
    }

    /**
     * Converts a single API method into an OpenAPI 3.1 path item entry.
     *
     * @param APIMethodInterface $method
     * @return array<string, array<string, mixed>> Path as key, path item object as value.
     *         E.g.: `['/api/GetComtypes' => ['post' => [...]]]`
     */
    public function convertMethod(APIMethodInterface $method) : array
    {
        $methodName = $method->getMethodName();
        $path = '/api/'.$methodName;

        $paramConverter = new ParameterConverter($method);
        $paramResult = $paramConverter->convertParameters($method->manageParams());

        $operation = $this->buildOperation($method, $methodName, $paramResult);

        return array(
            $path => array(
                'post' => $operation,
            ),
        );
    }

    /**
     * Builds the OpenAPI operation object for the given method.
     *
     * @param APIMethodInterface $method
     * @param string $methodName Pre-resolved method name.
     * @param array{parameters: array<int, array<string,mixed>>, requestBodyProperties: array<string, array<string,mixed>>, requiredBodyProperties: string[]} $paramResult
     * @return array<string, mixed>
     */
    private function buildOperation(APIMethodInterface $method, string $methodName, array $paramResult) : array
    {
        $description = $method->getDescription();
        $summary = $this->extractFirstLine($description);

        $operation = array(
            'operationId' => $methodName,
            'summary' => $summary,
            'description' => $description,
            'tags' => array($method->getGroup()->getLabel()),
            'parameters' => $this->buildParameters($method, $paramResult['parameters']),
            'responses' => $this->responseConverter->convertResponses($method),
        );

        // Add request body for JSON body methods.
        if($method instanceof JSONRequestInterface && !empty($paramResult['requestBodyProperties']))
        {
            $operation['requestBody'] = $this->buildRequestBody(
                $method->getRequestMime(),
                $paramResult['requestBodyProperties'],
                $paramResult['requiredBodyProperties']
            );
        }

        // Optional: x-extensions.
        $changelog = $method->getChangelog();
        if(!empty($changelog))
        {
            $operation['x-changelog'] = $changelog;
        }

        $relatedMethodNames = $method->getRelatedMethodNames();
        if(!empty($relatedMethodNames))
        {
            $operation['x-related-methods'] = $relatedMethodNames;
        }

        // Optional: external documentation.
        $docUrl = (string)$method->getDocumentationURL();
        if($docUrl !== '')
        {
            $operation['externalDocs'] = array(
                'url' => $docUrl,
            );
        }

        // Authentication: apply security requirement for methods that need an API key.
        if($method instanceof APIKeyMethodInterface)
        {
            $operation['security'] = array(
                array(OpenAPISchema::SECURITY_SCHEME_API_KEY => array()),
            );
        }

        // Validation rules: document parameter constraints as x-validation-rules.
        $rules = $method->manageParams()->getRules();
        if(!empty($rules))
        {
            $operation['x-validation-rules'] = $this->buildValidationRulesData($rules);
        }

        return $operation;
    }

    /**
     * Builds the parameters array, prepending the global `apiVersion` query parameter.
     *
     * The `apiVersion` parameter is added manually here because {@see ParameterConverter}
     * intentionally excludes reserved parameters from per-method conversion.
     *
     * @param APIMethodInterface $method
     * @param array<int, array<string,mixed>> $convertedParams Already-converted per-method parameters.
     * @return array<int, array<string,mixed>>
     */
    private function buildParameters(APIMethodInterface $method, array $convertedParams) : array
    {
        $apiVersionParam = array(
            'name' => APIMethodInterface::REQUEST_PARAM_API_VERSION,
            'in' => 'query',
            'required' => false,
            'description' => 'API version to use. Defaults to the current version when omitted.',
            'schema' => array(
                'type' => 'string',
                'enum' => $method->getVersions(),
                'default' => $method->getCurrentVersion(),
            ),
        );

        return array_merge(array($apiVersionParam), $convertedParams);
    }

    /**
     * Builds the OpenAPI request body object for a JSON body method.
     *
     * @param string $contentType MIME type from `getRequestMime()`.
     * @param array<string, array<string,mixed>> $properties Schema properties.
     * @param string[] $requiredProperties Names of required properties.
     * @return array<string,mixed>
     */
    private function buildRequestBody(string $contentType, array $properties, array $requiredProperties) : array
    {
        $schema = array(
            'type' => 'object',
            'properties' => $properties,
        );

        if(!empty($requiredProperties))
        {
            $schema['required'] = $requiredProperties;
        }

        return array(
            'required' => true,
            'content' => array(
                $contentType => array(
                    'schema' => $schema,
                ),
            ),
        );
    }

    /**
     * Extracts the first non-empty line from a multi-line description string.
     *
     * Used to produce the OpenAPI `summary` field, which must be a single line.
     *
     * @param string $description Full description, possibly multi-line.
     * @return string First non-empty line, or the full string if no newlines.
     */
    private function extractFirstLine(string $description) : string
    {
        $lines = explode("\n", $description);
        foreach($lines as $line)
        {
            $trimmed = trim($line);
            if($trimmed !== '')
            {
                return $trimmed;
            }
        }

        return $description;
    }

    /**
     * Converts a collection of validation rules into an `x-validation-rules` array
     * suitable for inclusion in an OpenAPI operation object.
     *
     * Each entry provides a human-readable description of the constraint so that
     * API consumers understand the inter-parameter dependencies.
     *
     * @param RuleInterface[] $rules
     * @return array<int, array<string, mixed>>
     */
    private function buildValidationRulesData(array $rules) : array
    {
        $result = array();

        foreach($rules as $rule)
        {
            $result[] = $this->buildSingleRuleData($rule);
        }

        return $result;
    }

    /**
     * Converts a single validation rule into a structured documentation array.
     *
     * Produces type-specific, human-readable descriptions for the known rule types:
     * - {@see OrRule}: "At least one of the following parameters must be provided: …"
     * - {@see RequiredIfOtherIsSetRule}: "If '{other}' is set, '{target}' is required."
     * - All other rules: falls back to `getLabel()` and `getTypeDescription()`.
     *
     * @param RuleInterface $rule
     * @return array<string, mixed>
     */
    private function buildSingleRuleData(RuleInterface $rule) : array
    {
        $paramNames = array_map(
            static fn($param) => $param->getName(),
            $rule->getParams()
        );

        if($rule instanceof OrRule)
        {
            $description = sprintf(
                'At least one of the following parameters must be provided: %s.',
                implode(', ', $paramNames)
            );
        }
        elseif($rule instanceof RequiredIfOtherIsSetRule)
        {
            $params = $rule->getParams();
            $description = sprintf(
                'If "%s" is set, "%s" is required.',
                $params[1]->getName(),
                $params[0]->getName()
            );
        }
        else
        {
            $typeDesc = $rule->getTypeDescription();
            $description = $typeDesc !== '' ? $typeDesc : $rule->getLabel();
        }

        return array(
            'id' => $rule->getID(),
            'label' => $rule->getLabel(),
            'description' => $description,
            'parameters' => $paramNames,
        );
    }
}
